import { Html, Head, Main, NextScript } from 'next/document'


export default function Document() {
  return (
    <Html lang="en">
      <Head />

      <body>



     
      
        {/* <Home/> */}
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
// import '@/styles/globals.css'


// import { Inter } from 'next/font/google'
// import Navbar from '../components/Navbar/Navbar'
// // import About from '../components/About/About'
// // import Quote from '../components/Quote/Quote'
// import Footer from'../components/Footer/Footer'
// import Index from "./index"


// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (

//     <div>
//     <html lang="en">
        
//       <body className={inter.className}>

//         <Navbar />
       
//         {/* <About/>
//         <Quote/> */}
//         <Index/>
//         {children}
//     <Footer/>
//       </body>

//     </html>
//     </div>
//   )
// }

